### PR TITLE
Flatten the examples folder structure

### LINKED ISSUE #114: [DISCUSS] Flatten the examples folder structure
I remember when we have introduced the nested structure for the example. The goal was to list high level concerns and implement a few examples by concern.

Looking back at this and also in the light of other projects having such example repositories, I believe we should roll back and flatten the structure. Just one folder per example with a relevant name. The concern constraint does no scale.

I can open a PR for this if we get enough buy-in on this issue.

WDYT?

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #114

### CODE REVIEW

**Comment by fcollonval** [comment]
CI errors are the expected one due to link pointing to moved file not existing on master branch yet.

**Review by jtpio — APPROVED** [review]
Looks good, thanks!

**Comment by jtpio** [comment]
Looks like this needs a rebase now that https://github.com/jupyterlab/extension-examples/pull/148 is merged.

**Comment by jtpio** [comment]
Ah looks like it needs a new rebase.

**Comment by fcollonval** [comment]
@jtpio I think this time we are good to go?

**Comment by jtpio** [comment]
Yes, thanks a lot for this!

We can double check the links check passes after the PR is merged.

**Review by jtpio — APPROVED** [review]

**Comment by jtpio** [comment]
So the check fails on master too: https://github.com/jupyterlab/extension-examples/runs/1926034761

Which could be related to going two times up in the folder hierarchy  (``../../``)

**Comment by fcollonval** [comment]
Thanks

I'll push a correction for the links

**Comment by jtpio** [comment]
Sounds good, thanks!

**Pull request merged**
