### PR TITLE
Localization for datagrid example

### PR DESCRIPTION
**Pull request by kgoo124**
Bumped packages and added in the `ITranslator`.

See #111

### CODE REVIEW

**Comment by kgoo124** [comment]
@goanpeca ready for review

**Comment by goanpeca** [comment]
Thanks a lot for the updates. Code looks good!

Are you seeing any errors when inspecting the console locally? 

---

@blink1073 are these failure related to some update needed on the examples?

**Review by goanpeca — APPROVED** [review]
👍

**Comment by kgoo124** [comment]
@goanpeca  @blink1073  No errors on the console

**Comment by goanpeca** [comment]
https://github.com/jupyterlab/extension-examples/pull/113 seems to display them so I guess this is not caused by your PR work @kgoo124

**Comment by blink1073** [comment]
I'm not sure about the errors, I was going to take a closer look tomorrow.

**Comment by fcollonval** [comment]
Hey actually the CI error comes from the JupyterLab installed. The CI script is looping on all examples and is installing the non-pre JupyterLab version (aka v2). So during the transition, I advice to duplicate the task and split the matrix example depending on their need for the v2 or v3. 

But this also suggest that a branch v3 should be created to let master untouch for v2 (similarly to the cookiecutter).

What do you think? @jtpio @echarles @blink1073

**Comment by jtpio** [comment]
> But this also suggest that a branch v3 should be created to let master untouched for v2 (similarly to the cookiecutter).

Sounds like it would make sense, since these are features from 3.0. And then merge `3.0` into master at the end of the month (https://github.com/jupyterlab/jupyterlab/issues/8038 for more info)

**Comment by jtpio** [comment]
> But this also suggest that a branch v3 should be created to let master untouched for v2 (similarly to the cookiecutter).

And we could update CI to use 3.0 only instead of duplicating the tasks.

**Comment by blink1073** [comment]
I agree, separate branch with a tweak in CI to install pre or stable.

**Comment by kgoo124** [comment]
@jtpio @blink1073 ready for merge

**Comment by jtpio** [comment]
Thanks @kgoo124 for updating the PR :+1: 

It looks like we would also need to update the embedded code snippets in the readme file, which was caught by this job:

https://github.com/jupyterlab/extension-examples/pull/112/checks?check_run_id=1122478637

**Comment by jtpio** [comment]
> It looks like we would also need to update the embedded code snippets 

Which means updating the `// src/index.ts#LXX-LYY` annotations to make sure they match the correct lines, and running `jlpm run embedme`.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
