### PR TITLE
Update master to JupyterLab 4 examples

### PR DESCRIPTION
**Pull request by fcollonval**
Upgrade example for JupyterLab 4

Switch to extension template (https://github.com/jupyterlab/extension-examples/pull/229)
Add notifications example (https://github.com/jupyterlab/extension-examples/pull/230)
Add an example package for the use of metadata-form (https://github.com/jupyterlab/extension-examples/pull/208)
Add codemirror extension example (https://github.com/jupyterlab/extension-examples/pull/231)

### CODE REVIEW

**Comment by diegoPlain** [comment]
Hi @fcollonval, I am using this repo for a couple of months now, and I would like to ask you if this PR is going forward, as right now it will fix the CI & repo, and allow the users to play with these examples.

Do you have any schedule in mind to approve it? Thanks in advance.

**Comment by fcollonval** [comment]
Hey @diegoPlain this PR will make the 4.0 branch the default _main_ branch. So you can definitely work with the 4.0 branch for now (same if you want to push a PR).

I would like to get #226 done (this requires some upstream fix and a 3.6.x release) as it is a required step towards fixing the document example (failing on 4.0 too).

**Comment by fcollonval** [comment]
Remaining failures can finally be ignored and we can merge this...

**Comment by ibdafna** [comment]
Thank you for maintaining this repo ❤️

**Pull request merged**
