### PR TITLE
Localization for kernel-output example

### PR DESCRIPTION
**Pull request by kgoo124**
See #111

### CODE REVIEW

**Comment by blink1073** [comment]
@kgoo124 mind holding off on these until we implement #115, since we'll have to target them to the 3.0 branch?

**Comment by kgoo124** [comment]
@blink1073 sure thing, sorry about that. just ping me when everything is set up!

**Comment by blink1073** [comment]
Will do!

**Review by goanpeca — APPROVED** [review]
Thanks for working on this @kgoo124 ! :-) 

LGTM

**Comment by jtpio** [comment]
Thanks @kgoo124 @blink1073 @goanpeca for working on this.

Would it be possible to update the PR to target the new `3.0` branch?

**Comment by kgoo124** [comment]
@jtpio ready for merge

**Comment by kgoo124** [comment]
@jtpio ready for merge

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
