### PR TITLE
[WIP] Run build_all CI job on Windows and Mac

### PR DESCRIPTION
**Pull request by jtpio**
We should check whether the examples can be built on Windows and Mac too.

### CODE REVIEW

**Comment by echarles** [comment]
this will prolly fail for now on windows because of #23

**Comment by jtpio** [comment]
Exactly :)

Will rebase when https://github.com/jtpio/jupyterlab-extension-examples/pull/23 is merged.

**Comment by jtpio** [comment]
Windows is still failing, but for a different reason now.

**Comment by echarles** [comment]
The log shows the following.

```
$ jupyter lab build --debug
[LabBuildApp] Searching ['D:\\a\\jupyterlab-extension-examples\\jupyterlab-extension-examples', 'C:\\Users\\runneradmin\\.jupyter', 'c:\\hostedtoolcache\\windows\\python\\3.7.5\\x64\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
##[error]Process completed with exit code 1.
```

I have explicitly set the `--debug` flag to get details in case of failure but here it does not say much.

I have not worked on windows since ages. Anyone having windows at hand so run the build all command?

**Comment by jtpio** [comment]
I was also hoping we would get more details with the `--debug` flag.

Same here, no Windows machine around.

**Comment by fcollonval** [comment]
I tested the commands on my Windows machine and everything ran fine 😞

**Comment by jtpio** [comment]
And according to the docs, the runners for each platform should have the same specs: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

So it's not even like the Windows job has less memory available.

**Comment by echarles** [comment]
The details of the `windows-latest` used by github actions can be found on https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019

It is a windows server 2019. If we can find find a windows server 2019 to replicate, an idea would be to create a Miniconda env (miniconda is available) with nodejs, yarn... pinned and see if we have more success

**Comment by jtpio** [comment]
Rebased on the latest `master` to see if the build is still failing on Windows.

Also tried:

- reducing the lerna concurrency with  `jlpm run link --concurrency=2` to see if the number of child processes could be the cause
- using node 12 instead of 10 (for the new default heap limits)

But it is still failing on Windows.

**Comment by jtpio** [comment]
It is failing at the `jlpm link-ext` step, before we even get the following lines:

```
lerna info versioning independent
lerna info Executing command in 15 packages: "jlpm run link"
```

**Comment by jtpio** [comment]
Re-ordering the steps so `jlpm link-ext` runs before `jlpm lint:check`:

https://github.com/jtpio/jupyterlab-extension-examples/pull/28/checks?check_run_id=362098370

The outcome is different. 'link-ext` passes, but now the `jupyter lab build` step fails and exits with code 1. It looks like the process is being killed prematurely.

**Comment by echarles** [comment]
The build on windows is activated for `build_all`. Could we try building a single extension on windows and if it fails. Maybe the CPU/memory usage is over quota in windows case?

**Comment by fcollonval** [comment]
Hey I do not know why two jobs on MacOS were skipped (maybe I hit some limitations). But otherwise this is good to go.

The only limitation I left out is the extension installation checks on the server extension example for Windows.

**Comment by jtpio** [comment]
Wow, thanks @fcollonval for picking that up!

Looks like some have timed out so we can try to re-run them all one more time.

What was the key to get it to pass? `shell: bash` or updating node?

**Comment by fcollonval** [comment]
> What was the key to get it to pass? shell: bash or updating node?

Honestly, I don't know because the build_all worked out of the box with node js 12.x. So it may be due to internal software update.

Regarding bash, this is used for the single extension test to be able to use the same run commands (more specifically to use environment variables)

**Comment by echarles** [comment]
Awesome! Thx for tackling this @fcollonval

**Pull request merged**
