### PR TITLE
Update paths

### PR DESCRIPTION
**Pull request by afshin**
This PR updates `jtpio/jupyterlab-extension-examples` to `jupyterlab/extension-examples`

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @afshin!

Maybe we could also update the other generic urls? For example: 

https://github.com/jupyterlab/extension-examples/blob/ae231a28b281dc95fc0f1c32cb1c7d8295604f5b/launcher/package.json#L10

**Comment by afshin** [comment]
Hm, what should the example homepages be, though? Would they not remain the same?

**Comment by jtpio** [comment]
Maybe it's simpler if all of them point to https://github.com/jupyterlab/extension-examples.

**Comment by jtpio** [comment]
Just enabled GitHub Actions on that repository (they were disabled by default and not triggered by this PR).

**Pull request merged**
