### PR TITLE
Add check on CI to compare more files

### LINKED ISSUE #120: Add check on CI to compare more files
Follow-up to https://github.com/jupyterlab/extension-examples/pull/119

Starting from JupyterLab 3.0 extensions can now be installed via `pip`, which is the way described in these examples.

New files have been added to each example, such as `setup.py`, `MANIFEST.in` and `pyproject.toml`:

https://github.com/jupyterlab/extension-examples/tree/ab5aefa454408b5cc6155c89eed8cc4db641c564/basics/hello-world

One way to check they are all in sync would be to run the upgrade script as mentioned in https://github.com/jupyterlab/extension-examples/pull/119#issuecomment-692118012

Similar to this step:

https://github.com/jupyterlab/extension-examples/blob/e7054af18aee9970f717fe5f015449c338098a2a/.github/workflows/main.yml#L45-L50

### PR DESCRIPTION
**Pull request by fcollonval**
Fixes #120

This approach uses the suggestion of applying the upgrade script

### CODE REVIEW

**Comment by fcollonval** [comment]
Should we copy the following files in the upgrade script:

```
      - name: Check config files
        if: steps.filter.outputs.extension == 'true'
        run: |
          diff basics/hello-world/tsconfig.json ${EXAMPLE_FOLDER}/tsconfig.json
          diff basics/hello-world/.eslintignore ${EXAMPLE_FOLDER}/.eslintignore
          diff basics/hello-world/.eslintrc.js ${EXAMPLE_FOLDER}/.eslintrc.js
          diff basics/hello-world/.gitignore ${EXAMPLE_FOLDER}/.gitignore
```

so that this check can be removed?

**Comment by fcollonval** [comment]
This is ready for review

**Comment by jtpio** [comment]
> Should we copy the following files in the upgrade script:

Would that affect how the upgrade is script is run locally? For example would we need to set the EXAMPLE_FOLDER variable?

Maybe it's fine to keep them separate for now.

**Comment by fcollonval** [comment]
Closing as the structure evolved quite a lot

**Pull request closed without merging**
