### PR TITLE
Update package.json deps to rc2

### PR DESCRIPTION
**Pull request by jtpio**
Follow-up to https://github.com/jupyterlab/extension-examples/pull/125 to also update the versions in the `package.json` files.

### CODE REVIEW

**Comment by jasongrout** [comment]
Might as well do rc1, which has some fixes?

**Comment by jtpio** [comment]
Sounds good.

Although it would be nice to keep the same version number everywhere for these examples (`package.json`, `setup.py`, `pyproject.toml`), so maybe we can do the update in the cookiecutter and then use the upgrade script.

**Comment by jtpio** [comment]
> we can do the update in the cookiecutter and then use the upgrade script

Opened https://github.com/jupyterlab/extension-cookiecutter-ts/pull/100

**Comment by jtpio** [comment]
This also updates to TS 4 added in https://github.com/jupyterlab/extension-cookiecutter-ts/pull/99

**Pull request merged**
