### PR TITLE
Update all the examples

### PR DESCRIPTION
**Pull request by hbcarlos**
Follow-up to #157

### CODE REVIEW

**Comment by fcollonval** [comment]
Thanks for working on this @hbcarlos 

`prettier` is not complaining any more. But `jupyter labextension list` is not happy any more on Windows :'(

**Comment by hbcarlos** [comment]
What can we do to solve it?

**Comment by fcollonval** [comment]
I need to test on my Windows PC. Right now the error is not helpful.

**Comment by fcollonval** [comment]
@hbcarlos locally this is working when running the command in the Windows command. So my guess is that the error comes from the bash shell on Windows. I push a commit to separate os and run the commands on default os shell. Let's see what comes out.

**Comment by fcollonval** [comment]
It does not work - the Windows tests seems to pass. But they are actually failing:

```
JupyterLab v3.0.16
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError
```

**Comment by hbcarlos** [comment]
Oooh, I see. Thanks for looking into this @fcollonval. I'll try to look into this issue too.

**Comment by fcollonval** [comment]
pip is listing the extension :zany_face: 

I'm lost here. There is still one reason I see is that on windows we are dealing with multiple drive (python is on c:\ and the project files are on d:\). I know it can bring problem sometimes. Algthough this is unlikely.

**Comment by fcollonval** [comment]
Ok the trouble comes from the data files not being packaged on Windows - the _install_data_ step is not executed ?!

**Ubuntu**

```
  Building wheel for jupyterlab-examples-hello-world (PEP 517): started
  running bdist_wheel
  running ensure_targets
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/jupyterlab_examples_hello_world
  copying jupyterlab_examples_hello_world/_version.py -> build/lib/jupyterlab_examples_hello_world
  copying jupyterlab_examples_hello_world/__init__.py -> build/lib/jupyterlab_examples_hello_world
  running egg_info
  writing jupyterlab_examples_hello_world.egg-info/PKG-INFO
  writing dependency_links to jupyterlab_examples_hello_world.egg-info/dependency_links.txt
  writing requirements to jupyterlab_examples_hello_world.egg-info/requires.txt
  writing top-level names to jupyterlab_examples_hello_world.egg-info/top_level.txt
  reading manifest file 'jupyterlab_examples_hello_world.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'LICENSE'
  warning: no files found matching 'jupyter-config/jupyterlab_examples_hello_world.json'
  no previously-included directories found matching '**/node_modules'
  no previously-included directories found matching 'lib'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '.git' found anywhere in distribution
  warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
  writing manifest file 'jupyterlab_examples_hello_world.egg-info/SOURCES.txt'
  creating build/lib/jupyterlab_examples_hello_world/labextension
  copying jupyterlab_examples_hello_world/labextension/package.json -> build/lib/jupyterlab_examples_hello_world/labextension
  creating build/lib/jupyterlab_examples_hello_world/labextension/static
  copying jupyterlab_examples_hello_world/labextension/static/498.927df2a714a93f9f72c1.js -> build/lib/jupyterlab_examples_hello_world/labextension/static
  copying jupyterlab_examples_hello_world/labextension/static/568.895c8e378771400c599d.js -> build/lib/jupyterlab_examples_hello_world/labextension/static
  copying jupyterlab_examples_hello_world/labextension/static/remoteEntry.81749508a3311a605814.js -> build/lib/jupyterlab_examples_hello_world/labextension/static
  copying jupyterlab_examples_hello_world/labextension/static/style.js -> build/lib/jupyterlab_examples_hello_world/labextension/static
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world
  copying build/lib/jupyterlab_examples_hello_world/_version.py -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension
  copying build/lib/jupyterlab_examples_hello_world/labextension/package.json -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension/static
  copying build/lib/jupyterlab_examples_hello_world/labextension/static/568.895c8e378771400c599d.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension/static
  copying build/lib/jupyterlab_examples_hello_world/labextension/static/498.927df2a714a93f9f72c1.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension/static
  copying build/lib/jupyterlab_examples_hello_world/labextension/static/style.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension/static
  copying build/lib/jupyterlab_examples_hello_world/labextension/static/remoteEntry.81749508a3311a605814.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world/labextension/static
  copying build/lib/jupyterlab_examples_hello_world/__init__.py -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world
  running install_data
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world
  copying jupyterlab_examples_hello_world/labextension/package.json -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world
  copying install.json -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static
  copying jupyterlab_examples_hello_world/labextension/static/498.927df2a714a93f9f72c1.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static
  copying jupyterlab_examples_hello_world/labextension/static/remoteEntry.81749508a3311a605814.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static
  copying jupyterlab_examples_hello_world/labextension/static/style.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static
  copying jupyterlab_examples_hello_world/labextension/static/568.895c8e378771400c599d.js -> build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static
  running install_egg_info
  Copying jupyterlab_examples_hello_world.egg-info to build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0-py3.7.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/jupyterlab_examples_hello_world-0.1.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-14uuncjw/tmpiwzi4yre/jupyterlab_examples_hello_world-0.1.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'jupyterlab_examples_hello_world/__init__.py'
  adding 'jupyterlab_examples_hello_world/_version.py'
  adding 'jupyterlab_examples_hello_world/labextension/package.json'
  adding 'jupyterlab_examples_hello_world/labextension/static/498.927df2a714a93f9f72c1.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/568.895c8e378771400c599d.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/remoteEntry.81749508a3311a605814.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/style.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/install.json'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/package.json'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static/498.927df2a714a93f9f72c1.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static/568.895c8e378771400c599d.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static/remoteEntry.81749508a3311a605814.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.data/data/share/jupyter/labextensions/@jupyterlab-examples/hello-world/static/style.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/METADATA'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/WHEEL'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/top_level.txt'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for jupyterlab-examples-hello-world (PEP 517): finished with status 'done'
  Created wheel for jupyterlab-examples-hello-world: filename=jupyterlab_examples_hello_world-0.1.0-py3-none-any.whl size=19146
```  

**Windows**

```
  Building wheels for collected packages: jupyterlab-examples-hello-world
  Created temporary directory: C:\Users\RUNNER~1\AppData\Local\Temp\pip-wheel-6xs8f1wr
  Destination directory: C:\Users\RUNNER~1\AppData\Local\Temp\pip-wheel-6xs8f1wr
  Building wheel for jupyterlab-examples-hello-world (PEP 517): started
  Running command 'c:\hostedtoolcache\windows\python\3.7.9\x64\python.exe' 'c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmp0nsjr3d1'
  running bdist_wheel
  running ensure_targets
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\jupyterlab_examples_hello_world
  copying jupyterlab_examples_hello_world\_version.py -> build\lib\jupyterlab_examples_hello_world
  copying jupyterlab_examples_hello_world\__init__.py -> build\lib\jupyterlab_examples_hello_world
  running egg_info
  writing jupyterlab_examples_hello_world.egg-info\PKG-INFO
  writing dependency_links to jupyterlab_examples_hello_world.egg-info\dependency_links.txt
  writing requirements to jupyterlab_examples_hello_world.egg-info\requires.txt
  writing top-level names to jupyterlab_examples_hello_world.egg-info\top_level.txt
  reading manifest file 'jupyterlab_examples_hello_world.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'LICENSE'
  warning: no files found matching 'jupyter-config\jupyterlab_examples_hello_world.json'
  no previously-included directories found matching '**\node_modules'
  no previously-included directories found matching 'lib'
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyo' found anywhere in distribution
  warning: no previously-included files matching '.git' found anywhere in distribution
  warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
  writing manifest file 'jupyterlab_examples_hello_world.egg-info\SOURCES.txt'
  creating build\lib\jupyterlab_examples_hello_world\labextension
  copying jupyterlab_examples_hello_world\labextension\package.json -> build\lib\jupyterlab_examples_hello_world\labextension
  creating build\lib\jupyterlab_examples_hello_world\labextension\static
  copying jupyterlab_examples_hello_world\labextension\static\498.927df2a714a93f9f72c1.js -> build\lib\jupyterlab_examples_hello_world\labextension\static
  copying jupyterlab_examples_hello_world\labextension\static\568.895c8e378771400c599d.js -> build\lib\jupyterlab_examples_hello_world\labextension\static
  copying jupyterlab_examples_hello_world\labextension\static\remoteEntry.5fe8ccfccf1c05794cf4.js -> build\lib\jupyterlab_examples_hello_world\labextension\static
  copying jupyterlab_examples_hello_world\labextension\static\style.js -> build\lib\jupyterlab_examples_hello_world\labextension\static
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\jupyterlab_examples_hello_world
  creating build\bdist.win-amd64\wheel\jupyterlab_examples_hello_world\labextension
  copying build\lib\jupyterlab_examples_hello_world\labextension\package.json -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world\labextension
  creating build\bdist.win-amd64\wheel\jupyterlab_examples_hello_world\labextension\static
  copying build\lib\jupyterlab_examples_hello_world\labextension\static\498.927df2a714a93f9f72c1.js -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world\labextension\static
  copying build\lib\jupyterlab_examples_hello_world\labextension\static\568.895c8e378771400c599d.js -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world\labextension\static
  copying build\lib\jupyterlab_examples_hello_world\labextension\static\remoteEntry.5fe8ccfccf1c05794cf4.js -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world\labextension\static
  copying build\lib\jupyterlab_examples_hello_world\labextension\static\style.js -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world\labextension\static
  copying build\lib\jupyterlab_examples_hello_world\_version.py -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world
  copying build\lib\jupyterlab_examples_hello_world\__init__.py -> build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world
  running install_egg_info
  Copying jupyterlab_examples_hello_world.egg-info to build\bdist.win-amd64\wheel\.\jupyterlab_examples_hello_world-0.1.0-py3.7.egg-info
  running install_scripts
  creating build\bdist.win-amd64\wheel\jupyterlab_examples_hello_world-0.1.0.dist-info\WHEEL
  creating 'C:\Users\RUNNER~1\AppData\Local\Temp\pip-wheel-6xs8f1wr\tmpoqcca9w2\jupyterlab_examples_hello_world-0.1.0-py3-none-any.whl' and adding 'build\bdist.win-amd64\wheel' to it
  adding 'jupyterlab_examples_hello_world/__init__.py'
  adding 'jupyterlab_examples_hello_world/_version.py'
  adding 'jupyterlab_examples_hello_world/labextension/package.json'
  adding 'jupyterlab_examples_hello_world/labextension/static/498.927df2a714a93f9f72c1.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/568.895c8e378771400c599d.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/remoteEntry.5fe8ccfccf1c05794cf4.js'
  adding 'jupyterlab_examples_hello_world/labextension/static/style.js'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/METADATA'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/WHEEL'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/top_level.txt'
  adding 'jupyterlab_examples_hello_world-0.1.0.dist-info/RECORD'
  removing build\bdist.win-amd64\wheel
  Building wheel for jupyterlab-examples-hello-world (PEP 517): finished with status 'done'
  Created wheel for jupyterlab-examples-hello-world: filename=jupyterlab_examples_hello_world-0.1.0-py3-none-any.whl size=12087
```

**Comment by fcollonval** [comment]
On Windows `print(setup_args['data_files'])` prints `[]`, so something is probably wrong in `jupyter_packaging.get_data_files`

**Comment by fcollonval** [comment]
Ok seems that the trouble come from a difference in behavior between `pathlib` and `os.path`

`os` is getting an absolute path like _C:\Users\RUNNER~1\AppData\Local\Temp\pip-req-build-vi810dlk_
`pathlib` is expanding the folder name and returns _C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-vi810dlk_

**Comment by fcollonval** [comment]
@jtpio @hbcarlos we are finally good to go on this one

**Comment by hbcarlos** [comment]
Wow, thank you soo much Frédéric!

**Review by jtpio — APPROVED** [review]
Wow thanks a lot @fcollonval and @hbcarlos for this one!

**Pull request merged**
