### PR TITLE
Cell toolbar

### PR DESCRIPTION
**Pull request by brichet**
Example to add cell toolbar buttons.

The buttons are displayed or not, depending on the cell type.

Fix https://github.com/jupyterlab/extension-examples/issues/227

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @brichet, this looks good!

**Comment by jtpio** [comment]
Looks like there are a couple of conflicts.

Also should the new example be listed in the top-level `README.md`? https://github.com/jupyterlab/extension-examples#develop-by-examples

**Comment by brichet** [comment]
Thanks @jtpio for looking this.

I rebased and fixed conflicts, and add la ink and a preview in README.

I also fixed 2 broken previews in README.

**Comment by brichet** [comment]
Tests are failing because https://github.com/jupyterlab/jupyterlab/pull/14838 is not merged yet.

Probably https://github.com/jupyterlab/extension-examples/pull/244 should have wait for it.

**Comment by jtpio** [comment]
> Probably #244 should have wait for it.

Right, I don't know why the failure was ignored in that PR.

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by fcollonval** [comment]
> > Probably #244 should have wait for it.
> 
> Right, I don't know why the failure was ignored in that PR.

It is a chicken egg issue - the lab doc reference the example that reference the lab doc.

**Comment by fcollonval** [comment]
Feel free to finish up the doc pr on lab.

**Pull request merged**
