### PR TITLE
Skip test if the extension is not touched

### PR DESCRIPTION
**Pull request by fcollonval**
This is a trial to take advantage of https://github.com/marketplace/actions/paths-filter for running CI only on modified extensions.

### CODE REVIEW

**Comment by fcollonval** [comment]
Commit 55fd650 seems to do the job.
Next steps: 
- [ ] Change slightly a file on an example
- [ ] Apply to the server-extension example

**Comment by fcollonval** [comment]
@jtpio @blink1073

I think this PR can be useful.

**Comment by jtpio** [comment]
Thanks @fcollonval!

+1 for having this, which would be useful when iterating on a single example at a time.

**Comment by jtpio** [comment]
We can then add it to the `3.0` branch too so the ongoing localization work can also make us of it.

**Review by jtpio — APPROVED** [review]

**Comment by fcollonval** [comment]
@meeseeksdev backport to 3.0

**Pull request merged**
