### PR TITLE
Update server extension entry points

### PR DESCRIPTION
**Pull request by fcollonval**
Following https://github.com/jupyterlab/extension-examples/issues/143#issuecomment-777392214
Update the example to use the correct extension entry point

### CODE REVIEW

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Maybe we'll also want to add a quick note for those who would like to maintain compatibility with the Classic Notebook server?

That would mean pointing to https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html?#extensionapp-as-a-classic-notebook-server-extension and placing data files in `jupyter_notebook_config.d`.

**Comment by fcollonval** [comment]
Good suggestion - I'll modify the PR to add that.

**Review by jtpio — APPROVED** [review]
Thanks!

**Pull request merged**
