### PR TITLE
Upgrade extensions for JupyterLab 3.0

### PR DESCRIPTION
**Pull request by blink1073**
Fixes https://github.com/jupyterlab/extension-examples/issues/115

Also adds a script that can be used in the future to upgrade the extensions: `scripts/upgrade_extensions.py`.  
I verified that re-running the script made no further changes.

063679ae79f462db08de2cabeaaf0353e32d77de and 55ea69b410da5e31640c61d03538d842af08fe15 demonstrate upgrading a server extension.  The first commit is the auto-upgrade of the `package.json` file, and the second is the result of manually upgrading the files as prompted by the upgrade script.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @goanpeca

**Comment by goanpeca** [comment]
Thanks @blink1073  :-)

**Comment by blink1073** [comment]
This is good to go!

**Comment by blink1073** [comment]
I'm seeing random failures due to yarnpkg.com timeouts

**Comment by jtpio** [comment]
Nice, thanks Steve!

Restarted the CI jobs and everything is green. This looks good to go so other PRs could target the `3.0` branch.

**Comment by jtpio** [comment]
Maybe we'll want to also add a CI step that checks the new files such as `pyproject.toml` and `setup.py` are in sync, similar to this one:

https://github.com/jupyterlab/extension-examples/blob/e7054af18aee9970f717fe5f015449c338098a2a/.github/workflows/main.yml#L47-L50

Although this might require using a custom script since the name of the extensions are also part of the `setup.py` file, and a plain `diff` might not be enough.

Something we could track in a separate issue.

**Comment by blink1073** [comment]
We could actually run the `script/upgrade_extension.py` and see if any files change in git status.  How does that sound?

**Comment by goanpeca** [comment]
Got for it :-)

**Comment by jtpio** [comment]
Sounds good :+1:

**Review by jtpio — APPROVED** [review]

**Pull request merged**
